/*
DO NOT EDIT THIS FILE

This file is meant to simulate a "database" data source.
There is nothing databasey about this file, it's just a placeholder.
Pretend there are database things in here.

Ho Hum.

*/

const queryForPlayers = () => {
    const data = JSON.parse('[{"name":"Jonas Valenciunas","age":26,"job":"Center","salary":"4.66m"},{"name":"Kyle Lowry","age":32,"job":"Point Guard","salary":"28.7m"},{"name":"Demar DeRozan","age":28,"job":"Shooting Guard","salary":"26.54m"},{"name":"Jakob Poeltl","age":22,"job":"Center","salary":"2.704m"}]');
    return data;
}

module.exports = queryForPlayers;